djangoBlog/djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("djangoBlogApp.urls", namespace="blog"))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoBlog/djangoBlogApp/urls.py
from django.urls import path
from . import views
app_name="djangoBlogApp"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('author/<name>', views.getAuthor.as_view(), name="author"),
    path('article/<int:id>', views.getSingle.as_view(), name="single_post"),
    path('category/<name>', views.getCategory, name="topic"),
    path('login', views.getLogin.as_view(), name="login"),
    path('logout', views.getLogout, name="logout"),
    path('create/', views.getCreate, name="create"),
    path('profile', views.getProfile, name="profile"),
    path('update/<int:pid>', views.getUpdate, name="update"),
    path('delete/<int:pid>', views.getDelete, name="delete"),
    path('register', views.getRegister, name="register"),
    path('topics', views.getTopic, name="category"),
    path('create/topic', views.createTopic, name="createTopic")
]

djangoBlog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

    {% load static %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">
    {% block stylesheet %}
    
    {% endblock %}

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Programming Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
          </li>
          <ul class="navbar-nav ml-auto ml-md-0">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg class="svg-inline--fa fa-user fa-w-14 fa-fw" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg=""><path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path></svg><!-- <i class="fas fa-user fa-fw"></i> --></a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item" href="{% url 'blog:create' %}">Buat Artikel</a>
            <a class="dropdown-item" href="{% url 'blog:profile' %}">Artikel Saya</a>
							<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'blog:logout' %}">Logout</a>
					</div>
				</li>
				{% block profile %}

       			{% endblock %}
			</ul>
        </ul>
      </div>
    </div>
  </nav>
  
  <!-- Page Content -->
  <div class="container">

    <div class="row">

  {% block content %}

  {% endblock %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
 
  <!-- Footer -->
  <footer class="py-4 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Programming Blog 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  {% block script %}{% endblock %}

</body>

</html>

djangoBlog/templates/category.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <h3 class="my-4">Kategori : 
      <small>{{ cat.name }}</small>
    </h3><br>

    {% for obj in post %}
        <!-- Blog Post -->
        <div class="card mb-4">
        <img class="img-fluid" src="{{ obj.image.url }}" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title">{{ obj.title }}</h4>
            <p class="card-text"><strong>Kategori : <a href="{% url 'blog:topic' name=obj.category %}">{{ obj.category }}</a></strong></p>
            <p class="card-text">{{ obj.body | truncatewords:15 }}</p>
            <a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Diupload pada {{ obj.posted_on }} oleh
            <a href="{{ obj.get_author_url }}">{{ obj.article_author.name }}</a>
            <p>Tag :
              {% for tag in tags %}
                {% if tag in obj.tag.all %}
                  ({{ tag.name }})
                {% endif %}
              {% endfor %}
            </p>
        </div>
        </div>
    {% endfor %}

    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
      {% if post.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page=1">&larr; First</a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ post.previous_page_number }}">&larr; Older</a>
          </li>
          <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
          </li>
      {% endif %}

      <span class="current">
          Page {{ post.number }} of {{ post.paginator.num_pages }}.
      </span>

      {% if post.has_next %}
          <li class="page-item disabled">
              <a class="page-link" href="?page=1">&larr; Prev</a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ post.next_page_number }}">Next &rarr;</a>
          </li>
          <li class="page-item">
              <a class="page-link" href="?page={{ post.paginator.num_pages }}">Last &rarr;</a>
          </li>
      {% endif %}
  </ul>  

  </div>
  
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Pencarian</h5>
          <div class="card-body">
            <form action="" method="GET">
            <div class="input-group">
              <input type="text" name="key" class="form-control" placeholder="Masukkan kata kunci" value="{{ request.GET.key }}">
              <span class="input-group-btn">
                <button class="btn btn-secondary">Cari!</button>
              </span>
            </div>
          </form>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Kategori</h5>
          <div class="card-body">
            <div class="row">
                {% for cat in categories %}
              <div class="col-lg-6 md">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="{% url 'blog:topic' name=cat.name %}">{{ cat.name }}</a>
                  </li>
                </ul>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-2">
          <h5 class="card-header">Artikel Lainnya</h5>
          {% for obj in post %}
          <div class="card-body">
            <div class="card mb-2">
			  <img class="img-fluid" src="{{ obj.image.url }}" alt="Card image cap">
			  <div class="card-body">
				<h5 class="card-title">{{ obj.title }}</h5>
				<p class="card-text">{{ obj.body | truncatewords:5 }}</p>
				<a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
			  </div>
			</div>
          </div>
          {% endfor %}
        </div>

      </div>
  
{% endblock %}
{% block script %}

{% endblock %}
      

djangoBlog/templates/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
Create a new post
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
    <div class="container-fluid my-4">
        <form class="col-lg-6 offset-lg-3" method="POST" enctype="multipart/form-data">
            <h3>Create New Article</h3><br>
            {% csrf_token %}
        
            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
        
            <button class="btn btn-primary">Publish</button>
        </form>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/create_topics.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container-fluid my-4">
    <form class="col-lg-6 offset-lg-3" method="POST"">
        <h3>Add New Category</h3><br>
        {% csrf_token %}
    
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
        {% endfor %}
    
        <button class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/createauthor.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
Create author profile
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container-fluid my-4">
    <form class="col-lg-6 offset-lg-3" method="POST" enctype="multipart/form-data">
        <h3>Become Author</h3><br>
        {% csrf_token %}
    
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
        {% endfor %}
    
        <button class="btn btn-primary">Create Author</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/getAuthorInfo.html
{% extends 'base.html' %}
{% block title %}
Create author profile
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Create author</button>
    </form>
</div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/index.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">

    <h1 class="my-4">Programming Blog</h1><br>

    {% for obj in post %}
        <!-- Blog Post -->
        <div class="card mb-4">
        <img class="img-fluid" src="{{ obj.image.url }}" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title">{{ obj.title }}</h4>
            <p class="card-text"><strong>Kategori : <a href="{% url 'blog:topic' name=obj.category %}">{{ obj.category }}</a></strong></p>
            <p class="card-text">{{ obj.body | truncatewords:15 }}</p>
            <a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Diupload pada {{ obj.posted_on }} oleh
            <a href="{{ obj.get_author_url }}">{{ obj.article_author.name }}</a>
            <p>Tag :
              {% for tag in tags %}
                {% if tag in obj.tag.all %}
                  ({{ tag.name }})
                {% endif %}
              {% endfor %}
            </p>
        </div>
        </div>
    {% endfor %}

    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        {% if post.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&larr; First</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ post.previous_page_number }}">&larr; Older</a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
            </li>
        {% endif %}

        <span class="current">
            Page {{ post.number }} of {{ post.paginator.num_pages }}.
        </span>

        {% if post.has_next %}
            <li class="page-item disabled">
                <a class="page-link" href="?page=1">&larr; Prev</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ post.next_page_number }}">Next &rarr;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ post.paginator.num_pages }}">Last &rarr;</a>
            </li>
        {% endif %}
    </ul>   

  </div>
  
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Pencarian</h5>
          <div class="card-body">
            <form action="" method="GET">
            <div class="input-group">
              <input type="text" name="key" class="form-control" placeholder="Masukkan kata kunci" value="{{ request.GET.key }}">
              <span class="input-group-btn">
                <button class="btn btn-secondary">Cari!</button>
              </span>
            </div>
          </form>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Kategori</h5>
          <div class="card-body">
            <div class="row">
                {% for cat in categories %}
              <div class="col-lg-6 md">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="{% url 'blog:topic' name=cat.name %}">{{ cat.name }}</a>
                  </li>
                </ul>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-2">
          <h5 class="card-header">Artikel Lainnya</h5>
          {% for obj in post %}
          <div class="card-body">
            <div class="card mb-2">
			  <img class="img-fluid" src="{{ obj.image.url }}" alt="Card image cap">
			  <div class="card-body">
				<h5 class="card-title">{{ obj.title }}</h5>
				<p class="card-text">{{ obj.body | truncatewords:5 }}</p>
				<a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
			  </div>
			</div>
          </div>
          {% endfor %}
        </div>

      </div>
  
{% endblock %}
{% block script %}

{% endblock %}
      

djangoBlog/templates/login.html
{% extends 'base.html' %}
{% block title %}Please login{% endblock %}
{% block stylesheet %}
{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
  <div class="container-fluid my-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title col-lg-6 offset-lg-3">Login</h3><br>
      </div>
      <div class="panel-body col-lg-6 offset-lg-3">
          {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
            {% endif %}
        <form class="" action="" method="POST">
            {% csrf_token %}
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="user" class="form-control" id="username" placeholder="Username">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="pass" class="form-control" id="password" placeholder="Password">
          </div><br>

          <button type="submit" class="btn btn-primary">Login</button><br><br><br>
          <p>Are you new here? <a href="{% url 'blog:register' %}">Register now</a></p><br>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}

{% endblock %}

djangoBlog/templates/my_article.html
{% extends 'base.html' %}
{% block title %}
{{ user.name.get_full_name }}
{% endblock %}
{% block stylesheet %}
    <style>
    .alert {
    height: 50px;
    margin-top: 200px;
}
    </style>
{% endblock %}
{% block profile %}
    <!-- <div class="fh5co-bio">
			<figure>
				<img src="{{ user.profile_picture.url }}" alt="Free HTML5 Bootstrap Template" class="img-responsive">
			</figure>
			<h3 class="heading">About Me</h3>
			<h2>{{ user.name.get_full_name }}</h2>
            <h4>{{ user.name.email }}</h4>
			<p>{{ user.details }}</p>
			<ul class="fh5co-social">
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-instagram"></i></a></li>
			</ul>
		</div> -->
{% endblock %}
{% block content %}
    <div class="container my-4">
      <div class="card">
        <div class="card-header"><h3>Author : {{ user.name }}</h3></div>
        <div class="card-body">
          <h5 class="card-title">About :</h5>
          <p class="card-text">{{ user.details }}</p>
        </div>
      </div>
    </div>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    <br><br>
    <div class="container my-4">
        <a href="{% url 'blog:create' %}" class="btn btn-primary pull pull-right">Add new article</a><br><br>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Title</td>
            <td>Posted On</td>
            <td>Action</td>
        </tr>
        </thead>
        <tbody>
        {% for p in post %}
            <tr>
                <td>{{ p.title }}</td>
                <td>{{ p.posted_on }}</td>
                <td><a href="{% url 'blog:delete' pid=p.id %}">Delete</a>||<a href="{% url 'blog:update' pid=p.id %}">Edit</a></td>
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Author || {{ auth.name }}
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
    
{% endblock %}
{% block content %}
    <div class="col-md-8">

        <h3 class="my-4">Author : {{ auth.name }}</h3><br>
    
        {% for obj in post %}
            <!-- Blog Post -->
            <div class="card mb-4">
            <img class="img-fluid" src="{{ obj.image.url }}" alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title">{{ obj.title }}</h4>
                <p class="card-text"><strong>Kategori : {{ obj.category }}</strong></p>
                <p class="card-text">{{ obj.body | truncatewords:15 }}</p>
                <a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
                Diupload pada {{ obj.posted_on }} oleh
                <a href="{{ obj.get_author_url }}">{{ obj.article_author.name }}</a>
                <p>Tag :
                  {% for tag in tags %}
                    {% if tag in obj.tag.all %}
                      ({{ tag.name }})
                    {% endif %}
                  {% endfor %}
                </p>
            </div>
            </div>
        {% endfor %}

{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
Please register for new account
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
    <div class="container-fluid my-4">
        <form class="col-lg-6 offset-lg-3" method="post">
            <h3>Sign Up</h3><br>
            {% csrf_token %}
        
            {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
        
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/sample.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}

{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/single.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}

{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ post.title }}</h1>

        <!-- Author -->
        <p class="lead">
          Oleh
          <a href="{{ post.get_author_url }}">{{ post.article_author.name }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Diupload pada {{ post.posted_on }}</p>
        <p class="card-text"><strong>Kategori : <a href="{% url 'blog:topic' name=post.category %}">{{ post.category }}</a></strong></p>
        <p>Tag :
          {% for tag in tags %}
            {% if tag in post.tag.all %}
              ({{ tag.name }})
            {% endif %}
          {% endfor %}
        </p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{ post.image.url }}" alt="">

        <hr>

        <!-- Post Content -->
        <p>{{ post.body }}</p><br><br>
        

        <!-- Comments Form -->

      
        <div class="card">
          <h5 class="card-header">Komentar</h5>
          <div class="card-body">
          <div class="single_post_comment">
              {% for comment in comment %}
                  <div class="single_comment">
                      <h4><img src="http://icons.iconarchive.com/icons/icons8/ios7/512/Users-User-Male-2-icon.png" alt="" style="height: 27px;margin-right: 10px;">{{ comment.name }}</h4>
                      <p>{{ comment.post_comment }}</p><hr>
                  </div>
                  {% empty %}
                  <h3>Tidak ada komentar</h3>
              {% endfor %}
      
          </div>
          </div>
          </div><br>
      
          
            <form method="post">
                <h3>Berikan Komentar</h3>
                {% csrf_token %}
            
                {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
                {% endfor %}
            
                <button class="btn btn-primary">Submit</button><br><br>
            </form>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Pencarian</h5>
          <div class="card-body">
            <form action="" method="GET">
            <div class="input-group">
              <input type="text" name="key" class="form-control" placeholder="Masukkan kata kunci" value="{{ request.GET.key }}">
              <span class="input-group-btn">
                <button class="btn btn-secondary">Cari!</button>
              </span>
            </div>
          </form>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
                {% for cat in categories %}
              <div class="col-lg-6 md">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">{{ cat.name }}</a>
                  </li>
                </ul>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-2">
          <h5 class="card-header">Related Article</h5>
          {% for obj in related %}
          <div class="card-body">
            <div class="card mb-2">
			  <img class="card-img-top" src="{{ obj.image.url }}" alt="Card image cap">
			  <div class="card-body">
				<h5 class="card-title">{{ obj.title }}</h5>
				<p class="card-text">{{ obj.body | truncatewords:5 }}</p>
				<a href="{{ obj.get_single_url }}" class="btn btn-primary">Read More &rarr;</a>
			  </div>
			</div>
          </div>
          {% endfor %}
        </div>

      </div>
      
{% endblock %}
{% block script %}

{% endblock %}

djangoBlog/templates/topics.html
{% extends 'base.html' %}
{% block title %}
All topics
{% endblock %}
{% block stylesheet %}

{% endblock %}
{% block profile %}
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% if request.user.is_authenticated %}
        {% if request.user.is_staff or request.user.is_superuser %}
            <a href="{% url 'blog:createTopic' %}" class="btn btn-primary pull pull-right">Add new category</a>
        {% endif %}
    {% endif %}

    <table class="table table-striped">
        <thead>
        <tr>
            <td>Topics</td>

            {% if request.user.is_authenticated %}
                {% if request.user.is_staff or request.user.is_superuser %}
                    <td>Action</td>
                {% endif %}
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for t in topic %}
            <tr>
                <td><a href="{% url 'blog:topic' name=t.name %}">{{ t.name }}</a></td>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff or request.user.is_superuser %}
                        <td><a href="">Delete</a>||<a href="">Edit</a></td>
                    {% endif %}
                {% endif %}
            </tr>
        {% endfor %}

        </tbody>
</table>
    </div>
{% endblock %}
{% block script %}

{% endblock %}